set feed off
set linesize 100
set pagesize 200

-- Check PDB GISP tablespace usage with free space less than threshold
alter session set container=gisp;

SELECT F.TABLESPACE_NAME,
TO_CHAR((T.TOTAL_SPACE - F.FREE_SPACE),'999,999') "USED(MB)",
TO_CHAR(F.FREE_SPACE, '999,999') "FREE(MB)",
TO_CHAR(T.TOTAL_SPACE, '999,999') "TOTAL(MB)",
TO_CHAR((ROUND ((F.FREE_SPACE/T.TOTAL_SPACE)*100)),'999,99999')||' %' PERCENT_FREE 
FROM (
SELECT TABLESPACE_NAME, ROUND (SUM (BLOCKS*(SELECT VALUE/1024 FROM V$PARAMETER WHERE NAME = 'db_block_size')/1024)) FREE_SPACE 
FROM DBA_FREE_SPACE WHERE TABLESPACE_NAME NOT IN ('SYSTEM','SYSAUX','TEMP','USERS','UNDOTBS1','UNDOTBS2') GROUP BY TABLESPACE_NAME) F,
(SELECT TABLESPACE_NAME,ROUND(SUM (BYTES/1048576)) TOTAL_SPACE FROM DBA_DATA_FILES WHERE TABLESPACE_NAME NOT IN ('SYSTEM','SYSAUX','TEMP','USERS','UNDOTBS1','UNDOTBS2') GROUP BY TABLESPACE_NAME) T 
WHERE F.TABLESPACE_NAME = T.TABLESPACE_NAME AND (ROUND ((F.FREE_SPACE/T.TOTAL_SPACE)*100)) < 30;

exit

