set lines 200
set pages 200

column name format a30
column value format a150
column display_name format a30
column ISDEPRECATED format a5
column DESCRIPTION format a30


select NAME, VALUE 
from v$parameter2 where upper(name) in 
('COMPATIBLE',
'CONTROL_FILE_RECORD_KEEP_TIME',
'CONTROL_FILES',
'DB_FILE_NAME_CONVERT',
'LOG_FILE_NAME_CONVERT',
'DB_UNIQUE_NAME',
'DB_RECOVERY_FILE_DEST',
'LOG_ARCHIVE_CONFIG',
'LOG_ARCHIVE_DEST_1',
'LOG_ARCHIVE_DEST_2',
'LOG_ARCHIVE_DEST_STATE_1',
'LOG_ARCHIVE_DEST_STATE_2',
'LOG_ARCHIVE_TRACE',
'REMOTE_LOGIN_PASSWORDFILE',
'STANDBY_FILE_MANAGEMENT',
'DG_BROKER_CONFIG_FILE1',
'DG_BROKER_CONFIG_FILE2',
'DG_BROKER_START',
'SPFILE',
'DB_NAME',
'DB_UNIQUE_NAME',
'INSTANCE_NAME',
'FAL_SERVER',
'FAL_CLIENT',
'DB_CREATE_FILE_DEST',
'DB_CREATE_ONLINE_LOG_DEST_1'
 ) order by name
/


