-- Filename: gen_cr_user.sql
-- Arthur: James Cheung
-- 

set head off term on verif off feed off lines 99 pages 999

undef v_user

select 
 '-------- '||chr(10)||
 'create user '||username||chr(10)||
 'identified by '||lower(username)||'123 '||chr(10)||
 'default tablespace '||upper(DEFAULT_TABLESPACE)||chr(10)||
 'temporary tablespace '||upper(TEMPORARY_TABLESPACE)||chr(10)||
 'account unlock '||
 decode(PROFILE,'DEFAULT','','profile '||PROFILE) || ';'
from dba_users
where username = upper('&&v_user') 
/

select 'alter user &&v_user quota unlimited on '||upper(TABLESPACE_NAME) || ';'
from DBA_TS_QUOTAS
where username = upper('&&v_user') 
/

set serveroutput on

declare cursor version_cur
	is
	select version from v$instance;
	ver_rec version_cur%rowtype;
	ver varchar2(2);
	pwd varchar2(30);
begin
	open version_cur;
	loop
		fetch version_cur into ver_rec;
		exit when version_cur%notfound;
		ver := substr(ver_rec.version,1,2);
		if ver = '10' then
			select password into pwd from dba_users where username=upper('&&v_user');
			dbms_output.put_line('alter user ' || '&&v_user' || ' identified by values ' || '''' ||pwd|| '''' || ';');
		end if;
		if ver = '11' then
			select password into pwd from sys.user$ where name=upper('&&v_user');
			dbms_output.put_line('alter user ' || '&&v_user' || ' identified by values ' || '''' ||pwd|| '''' || ';');
		end if;
		
	end loop;
	close version_cur;
end;
/

prompt

--- Generated by dbms_metadata.get_ddl
-- set long 99999
-- select dbms_metadata.get_ddl('USER',upper('&&v_user')) || ';' from dual;


select 
  'grant '||GRANTED_ROLE||' to &&v_user ' || decode(admin_option,'YES','with admin option;',';')
from dba_role_privs 
where grantee=upper('&&v_user');

select 
  'grant '||PRIVILEGE||' to &&v_user ' || decode(admin_option,'YES','with admin option;',';')
from dba_sys_privs  
where grantee=upper('&&v_user');


select 
  'grant '||PRIVILEGE||' on '||owner||'.'||TABLE_NAME||' to '||GRANTEE|| ' ' || decode(grantable,'YES','with grant option ',' ') ||
decode(HIERARCHY,'YES','with hierarchy optiion;',';')
from DBA_TAB_PRIVS  
where grantee=upper('&&v_user') order by 1;


set feed on head on





