set serveroutput on
declare
  v_role VARCHAR2(30);
BEGIN
  select DATABASE_ROLE into v_role from V$DATABASE;
  if v_role = 'PRIMARY' then
        dbms_output.put_line('PRIMARY -> ALTER DATABASE OPEN -> ALTER PLUGGABLE DATABASE GISP OPEN READ WRITE');
        EXECUTE IMMEDIATE 'ALTER DATABASE OPEN';
        EXECUTE IMMEDIATE 'ALTER PLUGGABLE DATABASE GISP OPEN READ WRITE';
  else
    dbms_output.put_line('STANDBY -> ALTER DATABASE RECOVER MANAGED STANDBY DATABASE DISCONNECT FROM SESSIONE');
    EXECUTE IMMEDIATE 'ALTER DATABASE RECOVER MANAGED STANDBY DATABASE DISCONNECT FROM SESSION';
  end if;
END;
/


