-- filename: privs.sql

spool privs.log

set pages 200 lines 200
col granted_role format a30
col grantee format a30
col privilege format a40
col admin_option format a10
col table_name format a30
col grantable format a5
col hierarchy format a5
col owner format a20

prompt =============  Role privilegs  =====================

select granted_role, grantee from dba_role_privs 
where grantee not in (
'SYS',
'SYSTEM',
'SYSMAN',
'DBSNMP',
'PUBLIC',
'DBA',
'ADM_PARALLEL_EXECUTE_TASK',
'ANONYMOUS',
'APEX_030200',
'APEX_ADMINISTRATOR_ROLE',
'APEX_PUBLIC_USER',
'APPQOSSYS',
'AQ_ADMINISTRATOR_ROLE',
'AQ_USER_ROLE',
'CSW_USR_ROLE',
'CTXAPP',
'CTXSYS',
'CWM_USER',
'DATAPUMP_EXP_FULL_DATABASE',
'DATAPUMP_IMP_FULL_DATABASE',
'DBFS_ROLE',
'DELETE_CATALOG_ROLE',
'EXECUTE_CATALOG_ROLE',
'EXFSYS',
'EXP_FULL_DATABASE',
'FLOWS_FILES',
'GATHER_SYSTEM_STATISTICS',
'HS_ADMIN_EXECUTE_ROLE',
'HS_ADMIN_SELECT_ROLE',
'IMP_FULL_DATABASE',
'LBACSYS',
'LBAC_DBA',
'LOGSTDBY_ADMINISTRATOR',
'MDSYS',
'MGMT_USER',
'MGMT_VIEW',
'OEM_MONITOR',
'OLAPSYS',
'OLAP_DBA',
'OLAP_USER',
'OLAP_XS_ADMIN',
'ORACLE_OCM',
'ORDADMIN',
'ORDPLUGINS',
'ORDSYS',
'OUTLN',
'OWB$CLIENT',
'OWBSYS',
'PUBLIC',
'SELECT_CATALOG_ROLE',
'SPATIAL_CSW_ADMIN',
'SPATIAL_CSW_ADMIN_USR',
'SPATIAL_WFS_ADMIN',
'SPATIAL_WFS_ADMIN_USR',
'WFS_USR_ROLE',
'WMSYS',
'WM_ADMIN_ROLE',
'XDB',
'XDBADMIN'
) order by grantee
;

prompt =============  System privilegs  =====================

select privilege, grantee, admin_option from dba_sys_privs 
where grantee not in (
'SYS',
'SYSTEM',
'SYSMAN',
'DBSNMP',
'PUBLIC',
'DBA',
'ADM_PARALLEL_EXECUTE_TASK',
'ANONYMOUS',
'APEX_030200',
'APEX_ADMINISTRATOR_ROLE',
'APEX_PUBLIC_USER',
'APPQOSSYS',
'AQ_ADMINISTRATOR_ROLE',
'AQ_USER_ROLE',
'CSW_USR_ROLE',
'CTXAPP',
'CTXSYS',
'CWM_USER',
'DATAPUMP_EXP_FULL_DATABASE',
'DATAPUMP_IMP_FULL_DATABASE',
'DBFS_ROLE',
'DELETE_CATALOG_ROLE',
'EXECUTE_CATALOG_ROLE',
'EXFSYS',
'EXP_FULL_DATABASE',
'FLOWS_FILES',
'GATHER_SYSTEM_STATISTICS',
'HS_ADMIN_EXECUTE_ROLE',
'HS_ADMIN_SELECT_ROLE',
'IMP_FULL_DATABASE',
'LBACSYS',
'LBAC_DBA',
'LOGSTDBY_ADMINISTRATOR',
'MDSYS',
'MGMT_USER',
'MGMT_VIEW',
'OEM_MONITOR',
'OLAPSYS',
'OLAP_DBA',
'OLAP_USER',
'OLAP_XS_ADMIN',
'ORACLE_OCM',
'ORDADMIN',
'ORDPLUGINS',
'ORDSYS',
'OUTLN',
'OWB$CLIENT',
'OWBSYS',
'PUBLIC',
'SELECT_CATALOG_ROLE',
'SPATIAL_CSW_ADMIN',
'SPATIAL_CSW_ADMIN_USR',
'SPATIAL_WFS_ADMIN',
'SPATIAL_WFS_ADMIN_USR',
'WFS_USR_ROLE',
'WMSYS',
'WM_ADMIN_ROLE',
'XDB',
'XDBADMIN'
) order by grantee
;

col privilege format a20

prompt =============  Object privilegs  =====================

select privilege, owner, table_name, grantee, grantable, HIERARCHY from DBA_TAB_PRIVS 
where grantee not in (
'SYS',
'SYSTEM',
'SYSMAN',
'DBSNMP',
'PUBLIC',
'DBA',
'ADM_PARALLEL_EXECUTE_TASK',
'ANONYMOUS',
'APEX_030200',
'APEX_ADMINISTRATOR_ROLE',
'APEX_PUBLIC_USER',
'APPQOSSYS',
'AQ_ADMINISTRATOR_ROLE',
'AQ_USER_ROLE',
'CSW_USR_ROLE',
'CTXAPP',
'CTXSYS',
'CWM_USER',
'DATAPUMP_EXP_FULL_DATABASE',
'DATAPUMP_IMP_FULL_DATABASE',
'DBFS_ROLE',
'DELETE_CATALOG_ROLE',
'EXECUTE_CATALOG_ROLE',
'EXFSYS',
'EXP_FULL_DATABASE',
'FLOWS_FILES',
'GATHER_SYSTEM_STATISTICS',
'HS_ADMIN_EXECUTE_ROLE',
'HS_ADMIN_SELECT_ROLE',
'IMP_FULL_DATABASE',
'LBACSYS',
'LBAC_DBA',
'LOGSTDBY_ADMINISTRATOR',
'MDSYS',
'MGMT_USER',
'MGMT_VIEW',
'OEM_MONITOR',
'OLAPSYS',
'OLAP_DBA',
'OLAP_USER',
'OLAP_XS_ADMIN',
'ORACLE_OCM',
'ORDADMIN',
'ORDPLUGINS',
'ORDSYS',
'OUTLN',
'OWB$CLIENT',
'OWBSYS',
'PUBLIC',
'SELECT_CATALOG_ROLE',
'SPATIAL_CSW_ADMIN',
'SPATIAL_CSW_ADMIN_USR',
'SPATIAL_WFS_ADMIN',
'SPATIAL_WFS_ADMIN_USR',
'WFS_USR_ROLE',
'WMSYS',
'WM_ADMIN_ROLE',
'XDB',
'XDBADMIN'
) order by grantee
;




spool off




